main/urls.py
from django.urls import path
from main.views import dashboard, create_transaction, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, edit_transaction, remove_transaction, get_transaction_json_today, add_transaction_ajax, get_transaction_json_tomorrow, get_transaction_json_yesterday, format_last_login, format_today, financial_report, get_transaction_json_expenses, get_transaction_json_income, get_transaction_json_transfer, get_transaction_json_all

app_name = 'main'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('create-transaction', create_transaction, name='create_transaction'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-transaction/<int:id>', edit_transaction, name='edit_transaction'),
    path('remove/<int:id>', remove_transaction, name='remove_transaction'),
    path('get-transaction/', get_transaction_json_today, name='get_transaction_json_today'),
    path('add-transaction-ajax/', add_transaction_ajax, name='add_transaction_ajax'),
    path('get-transaction-tomorrow/', get_transaction_json_tomorrow, name='get_transaction_json_tomorrow'),
    path('get-transaction-yesterday/', get_transaction_json_yesterday, name='get_transaction_json_yesterday'),
    path('format-last-login/', format_last_login, name='format_last_login'),
    path('format-today/', format_today, name='format_today'),
    path('financial-report/', financial_report, name='financial_report'),
    path('get_transaction-json-expenses/', get_transaction_json_expenses, name='get_transaction_json_expenses'),
    path('get-transaction-json-income/', get_transaction_json_income, name='get_transaction_json_income'),
    path('get-transaction-json-transfer/', get_transaction_json_transfer, name='get_transaction_json_transfer'),
    path('get-transaction-json-all/', get_transaction_json_all, name='get_transaction_json_all'),

]

moneysaving/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    balance = models.DecimalField(max_digits=15, decimal_places=2, default=0.00)

    def __str__(self):
        return f"{self.user.username}'s Account"

class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    amount = models.DecimalField(max_digits=15, decimal_places=2)
    description = models.TextField()

    TRANSACTION_TYPES = [
        ('Income', 'Income'),
        ('Expense', 'Expense'),
        ('Transfer', 'Transfer')
    ]

    CATEGORY_CHOICES = [
        ('Transport', 'Transport'),
        ('Going out', 'Going Out'),
        ('Health', 'Health'),
        ('Groceries', 'Groceries'),
        ('Holiday', 'Holiday'),
        ('Children', 'Children'),
        ('Education', 'Education'),
        ('Gifts', 'Gifts'),
        ('Shopping', 'Shopping'),
        ('Sports', 'Sports'),
        ('Leisure', 'Leisure'),
        ('Savings', 'Savings'),
    ]

    category = models.CharField(max_length=30, choices=CATEGORY_CHOICES)
    transaction_type = models.CharField(max_length=30, choices=TRANSACTION_TYPES, blank=True, null=True)

    def __str__(self):
        return f"{self.amount} {self.get_category_display()} ({self.transaction_type}) - {self.timestamp}"

class Budget(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE, blank=True, null=True)
    amount = models.DecimalField(max_digits=15, decimal_places=2)

    def __str__(self):
        return f"{self.user.username}'s Budget"

main/forms.py
from django.forms import ModelForm
from main.models import Transaction

class TransactionForm(ModelForm):
    class Meta:
        model = Transaction
        fields = ["amount", "description", "transaction_type", 'category']

main/views.py
import datetime
from django.shortcuts import render, redirect
from .models import Account, Transaction, Budget
from django.http import HttpResponseRedirect
from main.forms import TransactionForm
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseNotFound
from django.utils import timezone
from django.http import JsonResponse
from django.db.models import Sum



@login_required(login_url='/login')
def dashboard(request):
    user = request.user
    transactions = Transaction.objects.filter(user=request.user)
    last_login_str = request.COOKIES.get('last_login')
    last_login_date = datetime.datetime.strptime(last_login_str, '%Y-%m-%d %H:%M:%S.%f')
    formatted_last_login = last_login_date.strftime('%d %B %Y')
    date_now = timezone.now().date()
    testing = date_now
    context = {
        'user': request.user.username,
        'account': 'account',
        'transactions': transactions,
        'budgets': 'budgets',
        'last_login': formatted_last_login,
        'date_now': date_now,
    }
    return render(request, 'main.html', context)

testing = timezone.now().date()

def switch_date(value):
    global testing  # Declare testing as a global variable
    if value == "tomorrow":
        testing = testing + timezone.timedelta(days=1)
    elif value == "yesterday":
        testing = testing - timezone.timedelta(days=1)
    elif value == "today":
        testing = timezone.now().date()

def edit_transaction(request, id):
    transaction = Transaction.objects.get(pk=id)

    form = TransactionForm(request.POST or None, instance= transaction)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:dashboard'))
    context = {'form':form}
    return render(request, "edit_transaction.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def remove_transaction(request, id):
    transaction = Transaction.objects.get(pk = id)
    transaction.delete()
    return HttpResponseRedirect(reverse('main:dashboard'))

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def create_transaction(request):
    form = TransactionForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        transaction = form.save(commit=False)
        transaction.user = request.user
        transaction.save()
        return HttpResponseRedirect(reverse('main:dashboard'))

    context = {'form': form}
    return render(request, "create_transaction.html", context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:dashboard")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def show_xml(request):
    data = Transaction.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Transaction.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Transaction.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Transaction.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def get_transaction_json_today(request):
    today = timezone.now().date()
    transaction_item = Transaction.objects.filter(timestamp__date=today, user=request.user)
    return HttpResponse(serializers.serialize('json', transaction_item))

def get_transaction_json_yesterday(request):
    switch_date("yesterday")
    yesterday = testing
    transaction_item = Transaction.objects.filter(timestamp__date=yesterday, user=request.user)
    return HttpResponse(serializers.serialize('json', transaction_item))

def get_transaction_json_tomorrow(request):
    switch_date("tomorrow")
    tomorrow = testing
    transaction_item = Transaction.objects.filter(timestamp__date=tomorrow, user=request.user)
    return HttpResponse(serializers.serialize('json', transaction_item))

def get_transaction_json_income(request):
    transaction_item = Transaction.objects.filter(timestamp__date=testing, user=request.user, category=Transaction.TRANSACTION_TYPES[0][1])
    return HttpResponse(serializers.serialize('json', transaction_item))

def get_transaction_json_expenses(request):
    transaction_item = Transaction.objects.filter(timestamp__date=testing, user=request.user, category=Transaction.TRANSACTION_TYPES[1][1])
    return HttpResponse(serializers.serialize('json', transaction_item))

def get_transaction_json_transfer(request):
    transaction_item = Transaction.objects.filter(timestamp__date=testing, user=request.user, category=Transaction.TRANSACTION_TYPES[2][1])
    return HttpResponse(serializers.serialize('json', transaction_item))

def get_transaction_json_all(request):
    transaction_item = Transaction.objects.filter(timestamp__date=testing, user=request.user)
    return HttpResponse(serializers.serialize('json', transaction_item))

def format_last_login(request):
    testing_str = testing.strftime('%Y-%m-%d')
    last_login_date = datetime.datetime.strptime(testing_str, '%Y-%m-%d')
    formatted_last_login = last_login_date.strftime('%d %B %Y')
    return JsonResponse({'formatted_last_login': formatted_last_login})

def format_today(request):
    today = timezone.now().date()
    switch_date("today")
    today_str = today.strftime('%Y-%m-%d')
    today_date = datetime.datetime.strptime(today_str, '%Y-%m-%d')
    formatted_today = today_date.strftime('%d %B %Y')
    return JsonResponse({'formatted_today': formatted_today})

def financial_report(request):
    # Filter transactions by type
    income = Transaction.objects.filter(timestamp__date=testing, user=request.user, category=Transaction.TRANSACTION_TYPES[0][1])
    expenses = Transaction.objects.filter(timestamp__date=testing, user=request.user, category=Transaction.TRANSACTION_TYPES[1][1])
    transfer = Transaction.objects.filter(timestamp__date=testing, user=request.user, category=Transaction.TRANSACTION_TYPES[2][1])

    # Calculate total amounts
    income_total = sum(transaction.amount for transaction in income) or 0
    expenses_total = sum(transaction.amount for transaction in expenses) or 0
    transfer_total = sum(transaction.amount for transaction in transfer) or 0

    return JsonResponse({
        'income_total': income_total,
        'expenses_total': expenses_total,
        'transfer_total': transfer_total,
    })



@csrf_exempt
def add_transaction_ajax(request):
    if request.method == 'POST':
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        transaction_type = request.POST.get("transaction_type")
        category = request.POST.get("category")
        user = request.user

        new_product = Transaction(amount=amount, description=description, transaction_type=transaction_type, category=category, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

main/templates/create_transaction.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_transaction.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>Edit Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}


{% block meta %}
    <title>FinCache - Login</title>
{% endblock meta %}

{% block content %}
<style>
    h1{
        color: #000000;
    }
    
    p {
        color: #000000;
    }
    
    .card {
        background-color: #F0FFFF;
    }
    
    .fincache-login-description {
        color: #F0FFFF;
    }
    
    .fincache-login-description h1 {
        font-size: 36px;
    }
    
    .fincache-login-description p {
        font-size: 20px;
    }
    
    .text-register a {
        text-decoration: none;
        color: #007bff;
    }
    
    .text-register a:hover {
        text-decoration: none;
        color: #15A3C7;
    }
    
    .card {
        background-color: #F0FFFF;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    
    body {
        background-color: #d6f3fb;
    }
</style>
<div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="row">
        <div class="col-md-6"> 
            <div class="fincache-login-description">
                <h1>FinCache</h1>
                <p>Elevate your fiscal fitness with FinCache, the quintessential digital ledger that revolutionizes your revenue rendezvous.</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Username:</label>
                            <input type="text" name="username" placeholder="Username" class="form-control">
                        </div>

                        <div class="form-group mt-3">
                            <label for="password">Password:</label>
                            <input type="password" name="password" placeholder="Password" class="form-control">
                        </div>

                        <div class="text-center mt-3 mb-3">
                            <input class="btn btn-primary px-4 py-2" type="submit" value="Login">
                        </div>
                    </form>

                    {% if messages %}
                        <ul>
                            {% for message in messages %}
                                <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    <p class="text-register">Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>FinCache - Register</title>
{% endblock meta %}

{% block content %}  

<style>
    h1{
        color: #000000;
    }

    p{
        color: #000000;
    }

    body {
        background-color: #d6f3fb;
    }
    
    .card {
        background-color: #F0FFFF;
    }
    
    .fincache-register-description {
        color: #F0FFFF;
    }

    .fincache-register-description h1 {
        font-size: 36px;
    }

    .fincache-register-description p {
        font-size: 20px;
    }

    .card {
        background-color: #F0FFFF;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
</style>

<div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="row">
        <div class="col-md-3"> 
            <div class="fincache-register-description">
                <h1>Sign Up</h1>
                <p>It's easy and quick.</p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <form method="POST">  
                        {% csrf_token %}  
                        <table>  
                            {{ form.as_table }}  
                            <tr>  
                                <td></td>
                                <td><input type="submit" name="submit" value="Daftar"/></td>  
                            </tr>  
                        </table>  
                    </form>
    
                    {% if messages %}  
                        <ul>   
                            {% for message in messages %}  
                                <li>{{ message }}</li>  
                            {% endfor %}  
                        </ul>   
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}